doc: Update build-docs script to make it easier to build Docbook docs.

diff --git a/doc/build-docs b/doc/build-docs
--- a/doc/build-docs
+++ b/doc/build-docs
@@ -27,20 +27,53 @@
 # (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 # THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
-PATH_TO_DOCS="/kdesvn/src/extragear/utils/kdesrc-build/doc/index.docbook"
-COMMON_FILES="'common/'" # The single quotes are exceedingly important
+# Turn on sanity checking
+set -e
+set -u
+# set -o pipefail is a bashism unfortunately
 
-# The kdelibs install process installs support files for DocBook handling to
-# the ksgmltools2 application data dir. A kdelibs checkout is not sufficient
-# since some of the xsl files are input to a CMake script which converts them
-# to final form.
-DATA_DIR=$(kde4-config --install data)
-DOC_SRCDIR="$DATA_DIR/ksgmltools2"
+PATH_TO_DOCS="./index.docbook"
+LANG_ISO3166_2="en"
+
+# The kdoctools install process installs support files for DocBook handling to
+# the application data dir. We need some of these xsl files for meinproc to
+# use.
+DATA_DIR=$(kf5-config --install data)
+DATA_DIR=${DATA_DIR%/} # Remove trailing /
+
+COMMON_DIR="kdoctools5-common"
+# The single quotes are exceedingly important for later. The dir path inside
+# the single quotes should be relative to make browser maximally happy; we use
+# a symlink later to make that possible but there's probably better ways to get
+# after this same goal
+BROWSER_COMMON=$(printf "'%s/'" "$COMMON_DIR")
+
+DOC_SRCDIR="$DATA_DIR/kf5/kdoctools"
 XSLT="$DOC_SRCDIR/customization/kde-chunk-online.xsl"
 
-# We need to run this from right directory, i.e. the directory we want generated
-# output to go to (www/kdesrc-build/documentation)
-meinproc4 --srcdir $DOC_SRCDIR \
-          --param kde.common="$COMMON_FILES" \
-          --stylesheet $XSLT \
-          $PATH_TO_DOCS
+# Check for obvious errors
+if [ ! -e "${PATH_TO_DOCS}" ]; then
+    echo "Unable to find Docbook file. Try running from the documentation directory!" >&2
+    exit 1
+fi
+
+if [ ! -e "${XSLT}" ]; then
+    echo "Unable to find documentation style template. Is kdoctools installed?" >&2
+    exit 1
+fi
+
+# We need to run this from right directory, i.e. the directory we want
+# generated output to go to. Ensure meinproc will find common files in this
+# directory.
+
+if [ ! -e "$COMMON_DIR" ]; then
+    ln -s "$DATA_DIR/doc/HTML/$LANG_ISO3166_2/$COMMON_DIR" .
+fi
+
+# Run meinproc to generate our output
+meinproc5 --srcdir "$DOC_SRCDIR"                  \
+          --param kde.common="$BROWSER_COMMON"    \
+          --param chunker.output.encoding="UTF-8" \
+          --param chunker.output.indent="yes"     \
+          --stylesheet "$XSLT"                    \
+          "$PATH_TO_DOCS"
